project_name: stylist

builds:
  - id: stylist
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: stylist
    format: binary

brews:
  - name: stylist
    tap:
      owner: twelvelabs
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula

    homepage: "https://github.com/twelvelabs/stylist"
    description: "Manage all your code quality tools with a single executable"
    license: "MIT"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  groups:
    - title: New features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 99

dockers:
  - image_templates:
      - "gcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    goarch: amd64
    use: buildx

  - image_templates:
      - "gcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
    use: buildx

docker_manifests:
  - name_template: "gcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "gcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "gcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-arm64"

  - name_template: "gcr.io/twelvelabs/{{ .ProjectName }}:latest"
    image_templates:
      - "gcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "gcr.io/twelvelabs/{{ .ProjectName }}:{{ .Tag }}-arm64"

report_sizes: true

snapshot:
  name_template: "{{ incpatch .Version }}-next" # cspell: disable-line
