project_name: stylist

builds:
  - id: stylist
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: stylist
    format: binary

brews:
  - name: stylist
    tap:
      owner: twelvelabs
      name: homebrew-tools
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula

    homepage: "https://github.com/twelvelabs/stylist"
    description: "Manage all your code quality tools with a single executable"
    license: "MIT"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next" # cspell: disable-line

changelog:
  use: github
  sort: asc
  groups:
    - title: New features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 99
