excludes:
  - dist/**
  - .cspellcache
  - coverage.out
output:
  # show_context: false
  # show_url: false
  # syntax_highlight: false
processors:
  - preset: cspell
  - preset: gitleaks
  - preset: golangci-lint
  - preset: gofmt
  - preset: markdownlint
  - preset: hadolint
  - preset: shellcheck
  - preset: shfmt
