---
excludes:
  - "**/tmp"

processors:
  # - name: "gofmt"
  #   includes:
  #     - "**/*.go"

  - name: "golangci-lint"
    preset: "golangci-lint"
    # includes:
    #   - "**/*.go"

  - name: "markdownlint"
    preset: "markdownlint"
    # includes:
    #   - "**/*.md"

  # - name: "shellcheck"
  #   includes:
  #     - "**/*.sh"

  # - name: "yamllint"
  #   includes:
  #     - "**/*.{yaml,yml}"
  #   excludes:
  #     - "**/secrets.yaml"
